### ISSUE TITLE
Writing a test function that tests cross correlation

### ISSUE THREAD

**Issue by haerynkim** [haerynkim/bme590hrm#9]
I imported the cross correlation function (numpy.correlate) so I'm not really sure how to write a test function that will check if the output values are actually what I should be getting. So I tried to hard-code inputs and expected responses and now I am getting a ValueError from the line assert response == expected.
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Any ideas for a better method to test imported packages? I have a similar problem with my imported peak detection method.

**Comment by dward2** [comment]
Please point to a specific test_function that you ran that gave this specific error.  That will better enable us to provide some feedback.

**Comment by haerynkim** [comment]
Used numpy.testing.assert_array_almost_equal to resolve rounding errors (close #9.)
